spring:
  application:
    name: goods-provider
  datasource:                    #设置数据源信息
    type: com.alibaba.druid.pool.DruidDataSource  #设置数据库连接池的类型
    driver-class-name: org.gjt.mm.mysql.Driver #设置数据库的驱动
    url: jdbc:mysql://127.0.0.1:3306/fr_states?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5            #设置最小连接数
      initial-size: 5        #设置当数据库连接池启动时，创建的连接数
      max-total: 10          #设置最大连接数据
      max-wait-millis: 2000        #设置最大等待时间
      
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml        #设置MyBatis中Mapper.xml文件的位置，SpringBootMapper.xml文件必须出现在src/main/resources目录下
  type-aliases-package: com.springcloud.entity   #设置mybatis实体类的位置
  configuration:
    map-underscore-to-camel-case: true    #设置Mybatis开启驼峰命名规则

#设置pagehelper分页插件    
pagehelper:
  helper-dialect: mysql     # 设置数据库类型
  reasonable: true          # 设置分页合理化参数：当pageNum<=0时，显示第1页。当pageNum>=总页数，显示最后一页
  support-methods-arguments: true 
